import { Experiment, ApparatusItem, VideoLesson } from "@/types";

export const experiments: Experiment[] = [
  {
    id: "animal-cell-001",
    title: "Animal Cell Explorer",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Cell Structure & Function",
    gradeLevel: "Grade 8",
    description:
      "Explore a detailed NIH-sourced animal cell in interactive 3D. Identify the nucleus, mitochondria, endoplasmic reticulum, and other organelles while learning how they work together.",
    thumbnail: "https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/animal-cell-nih.glb",
    modelScale: 1.2,
    tags: ["cell biology", "organelles", "animal cell", "NIH"],
  },
  {
    id: "neuron-001",
    title: "Neuron Structure & Synapse",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "The Nervous System",
    gradeLevel: "Grade 8",
    description:
      "Examine a medically accurate neuron model with visible axon, dendrites, and soma. Understand how nerve impulses travel through the nervous system.",
    thumbnail: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/neuron-nih.glb",
    modelScale: 1.5,
    tags: ["neuron", "nervous system", "anatomy", "NIH"],
  },
  {
    id: "bacteria-001",
    title: "Bacteria Cell Wall",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Microorganisms",
    gradeLevel: "Grade 7",
    description:
      "Visualize the protective cell wall of bacteria. Study peptidoglycan layers, flagella, and pili in this NIH-derived 3D model.",
    thumbnail: "https://images.unsplash.com/photo-1579165466949-3180a3d056d5?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/bacteria-wall-nih.glb",
    modelScale: 2.0,
    tags: ["bacteria", "microorganisms", "cell wall", "NIH"],
  },
  {
    id: "horse-001",
    title: "Horse Anatomy",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Animal Adaptations",
    gradeLevel: "Grade 7",
    description:
      "Study the skeletal and muscular structure of a horse. Observe how limb anatomy supports locomotion and weight-bearing in large mammals.",
    thumbnail: "https://images.unsplash.com/photo-1553284965-83fd3e82fa5a?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/horse.glb",
    modelScale: 0.015,
    hasAnimation: true,
    tags: ["mammals", "anatomy", "locomotion", "skeleton"],
  },
  {
    id: "fox-001",
    title: "Fox Specimen",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Animal Adaptations",
    gradeLevel: "Grade 6",
    description:
      "Examine a low-poly fox model to understand canine body proportions, tail structure for balance, and adaptations for predation.",
    thumbnail: "https://images.unsplash.com/photo-1474511320723-9a56873867b5?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/fox.glb",
    modelScale: 0.02,
    hasAnimation: true,
    tags: ["mammals", "canine", "adaptations", "predator"],
  },
  {
    id: "fish-001",
    title: "Barramundi Fish Anatomy",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Aquatic Life & Fish",
    gradeLevel: "Grade 7",
    description:
      "Investigate the streamlined body, fin placement, and scale patterns of the barramundi. Understand how form supports aquatic locomotion.",
    thumbnail: "https://images.unsplash.com/photo-1524704654690-b56c05c78a00?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/barramundi-fish.glb",
    modelScale: 8.0,
    tags: ["fish", "aquatic", "anatomy", "locomotion"],
  },
  {
    id: "mosquito-001",
    title: "Mosquito in Amber",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Insects & Fossils",
    gradeLevel: "Grade 8",
    description:
      "Study a mosquito preserved in amber. Observe insect anatomy including wings, proboscis, and compound eyes while learning about fossilization.",
    thumbnail: "https://images.unsplash.com/photo-1504392022767-a8fc0771f239?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/mosquito-in-amber.glb",
    modelScale: 3.0,
    tags: ["insects", "fossils", "amber", "paleontology"],
  },
  {
    id: "avocado-001",
    title: "Avocado Plant Structure",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Plant Reproduction",
    gradeLevel: "Grade 7",
    description:
      "Examine the seed, cotyledon, and outer skin of an avocado. Understand how dicot seeds store energy and support early plant growth.",
    thumbnail: "https://images.unsplash.com/photo-1523049673856-606ae93a9c9d?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/avocado.glb",
    modelScale: 8.0,
    tags: ["plants", "seeds", "dicot", "botany"],
  },
  {
    id: "flowers-001",
    title: "Glass Vase Flowers",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Plant Parts & Functions",
    gradeLevel: "Grade 6",
    description:
      "Study flower anatomy including petals, stem, and leaves. Learn about pollination structures and how flowers attract pollinators.",
    thumbnail: "https://images.unsplash.com/photo-1490750967868-88aa6f44c0e3?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/glass-vase-flowers.glb",
    modelScale: 3.0,
    tags: ["flowers", "plants", "pollination", "botany"],
  },
  {
    id: "brain-stem-001",
    title: "Brain Stem Anatomy",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "The Nervous System",
    gradeLevel: "Grade 8",
    description:
      "Explore the brain stem, cerebellum, and connecting neural pathways. Understand how this region controls vital autonomic functions.",
    thumbnail: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/brain-stem.glb",
    modelScale: 1.5,
    hasAnimation: true,
    tags: ["brain", "anatomy", "nervous system", "medical"],
  },
  {
    id: "tropical-plant-001",
    title: "Tropical Plant Adaptations",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Plant Adaptations",
    gradeLevel: "Grade 7",
    description:
      "Observe leaf structure, venation patterns, and stem morphology in a tropical plant model. Learn how plants adapt to humid environments.",
    thumbnail: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/diffuse-transmission-plant.glb",
    modelScale: 2.5,
    tags: ["plants", "tropical", "adaptations", "leaves"],
  },
  {
    id: "flamingo-001",
    title: "Flamingo Specimen",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Birds & Flight",
    gradeLevel: "Grade 6",
    description:
      "Study the long legs, curved beak, and wing structure of a flamingo. Understand adaptations for wading and filter-feeding in shallow lakes.",
    thumbnail: "https://images.unsplash.com/photo-1497206365907-f5e3f0e6fe99?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/flamingo.glb",
    modelScale: 0.015,
    hasAnimation: true,
    tags: ["birds", "flamingo", "adaptations", "wading"],
  },
  {
    id: "parrot-001",
    title: "Parrot Specimen",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Birds & Flight",
    gradeLevel: "Grade 6",
    description:
      "Examine the hooked beak, zygodactyl feet, and vibrant wing feathers of a parrot. Learn how these features support climbing and flight.",
    thumbnail: "https://images.unsplash.com/photo-1552728089-57bdde30beb8?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/parrot.glb",
    modelScale: 0.015,
    hasAnimation: true,
    tags: ["birds", "parrot", "flight", "feathers"],
  },
  {
    id: "stork-001",
    title: "Stork Specimen",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Birds & Flight",
    gradeLevel: "Grade 6",
    description:
      "Observe the long neck, broad wings, and sharp bill of a stork. Understand how body proportions support long-distance migration and wading.",
    thumbnail: "https://images.unsplash.com/photo-1504392022767-a8fc0771f239?w=800&q=80",
    assetType: "3d_model",
    modelUrl: "/models/stork.glb",
    modelScale: 0.015,
    hasAnimation: true,
    tags: ["birds", "stork", "migration", "wading"],
  },
  {
    id: "osmosis-video-001",
    title: "Osmosis in a Potato Cell",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Plant & Animal Nutrition",
    gradeLevel: "Grade 8",
    description:
      "Watch a step-by-step practical demonstration of osmosis using potato strips in hypotonic and hypertonic solutions.",
    thumbnail: "https://images.unsplash.com/photo-1592419044706-39796d40f98c?w=800&q=80",
    assetType: "video",
    videoUrl: "#",
    tags: ["osmosis", "diffusion", "practical"],
  },
  {
    id: "microscope-001",
    title: "Using a Light Microscope",
    subject: "Biology",
    strand: "Living Things & Their Environment",
    subStrand: "Observation & Classification",
    gradeLevel: "Grade 7",
    description:
      "Learn the parts and proper handling of a school light microscope. Focus techniques and slide preparation guide.",
    thumbnail: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80",
    assetType: "image",
    tags: ["microscope", "lab skills", "observation"],
  },
];

export const apparatus: ApparatusItem[] = [
  {
    id: "app-001",
    name: "Compound Light Microscope",
    category: "Observation",
    description:
      "Optical instrument used to magnify small objects. School grade with 40x–400x magnification.",
    imageUrl: "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=600&q=80",
    safetyNotes: "Always carry with both hands. Clean lenses with lens paper only.",
  },
  {
    id: "app-002",
    name: "Bunsen Burner",
    category: "Heating",
    description:
      "Laboratory gas burner producing a single open flame. Used for heating, sterilization, and combustion.",
    imageUrl: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=600&q=80",
    safetyNotes: "Tie back long hair. Never leave unattended. Check gas tubing for leaks.",
  },
  {
    id: "app-003",
    name: "Measuring Cylinder",
    category: "Measurement",
    description:
      "Graduated cylinder for measuring liquid volumes accurately. Read at eye level at the meniscus.",
    imageUrl: "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=600&q=80",
    safetyNotes: "Place on a flat surface. Do not use for mixing or heating.",
  },
  {
    id: "app-004",
    name: "Test Tube Rack",
    category: "Storage",
    description:
      "Holds multiple test tubes upright. Essential for organizing reactions and preventing spills.",
    imageUrl: "https://images.unsplash.com/photo-1608037521244-f1c6c7635194?w=600&q=80",
    safetyNotes: "Ensure tubes are cool before placing in rack.",
  },
  {
    id: "app-005",
    name: "Dropper / Pipette",
    category: "Transfer",
    description:
      "Used to transfer small volumes of liquid. Some have rubber bulbs; others use suction.",
    imageUrl: "https://images.unsplash.com/photo-1579154204601-01588f351e67?w=600&q=80",
    safetyNotes: "Never pipette by mouth in school labs. Use a bulb or pump.",
  },
];

export const videos: VideoLesson[] = [
  {
    id: "vid-001",
    title: "Osmosis in a Potato Cell",
    subject: "Biology",
    duration: "4:32",
    thumbnail: "https://images.unsplash.com/photo-1592419044706-39796d40f98c?w=600&q=80",
    videoUrl: "#",
    description:
      "Demonstrates water movement across a semi-permeable membrane using potato cylinders in salt solutions.",
  },
  {
    id: "vid-002",
    title: "Distillation of Dirty Water",
    subject: "Chemistry",
    duration: "6:15",
    thumbnail: "https://images.unsplash.com/photo-1544376798-89aa6b82c6cd?w=600&q=80",
    videoUrl: "#",
    description:
      "Simple distillation setup for separating mixtures and purifying water. Suitable for Grade 7 CBC.",
  },
  {
    id: "vid-003",
    title: "Testing for Starch in Leaves",
    subject: "Biology",
    duration: "5:48",
    thumbnail: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80",
    videoUrl: "#",
    description:
      "Iodine test procedure for photosynthesis experiments. Includes boiling, decolourization, and staining.",
  },
  {
    id: "vid-004",
    title: "Measuring Earthquake Waves",
    subject: "Geography",
    duration: "7:02",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80",
    videoUrl: "#",
    description:
      "Seismograph demonstration and interpretation of P-waves and S-waves in the Kenyan context.",
  },
];
